### ISSUE TITLE
[BUG] Version still shows 2.6.9, same as the original repo

### ISSUE THREAD

**Issue by lozalojo** [kckaiwei/TurnMarker#5]
At package.json and module.json

Please, change it to 2.7.0

Also, it would be a good idea to rename the repo and publish at foundryvtt.com

**Comment by kckaiwei** [comment]
Yeah. I did make a new repo like you suggested:

https://github.com/kckaiwei/TurnMarker-alt

And I'll look into getting that done. I've never "owned" a module, so not clear on the deployment, but will try to get that working ASAP.
